name: ResourcePAK
main: com.magmaguy.resourcepackmanager.ResourcePackManager
version: 1.8.0
api-version: '1.21.4'
authors: ["MagmaGuy", "GMOCookies"]
softdepend:
  - Geyser-Spigot

commands:
  resourcepackmanager:
    aliases:
      - rspm
    description: "Main command"
